use riti::keycodes::*;

pub fn char_to_keycode(ch: char) -> u16 {
    match ch {
        // Alphanumeric keys
        '`' => VC_GRAVE,
        '~' => VC_TILDE,
        '0' => VC_0,
        ')' => VC_PAREN_RIGHT,
        '1' => VC_1,
        '!' => VC_EXCLAIM,
        '2' => VC_2,
        '@' => VC_AT,
        '3' => VC_3,
        '#' => VC_HASH,
        '4' => VC_4,
        '$' => VC_DOLLAR,
        '5' => VC_5,
        '%' => VC_PERCENT,
        '6' => VC_6,
        '^' => VC_CIRCUM,
        '7' => VC_7,
        '&' => VC_AMPERSAND,
        '8' => VC_8,
        '*' => VC_ASTERISK,
        '9' => VC_9,
        '(' => VC_PAREN_LEFT,

        // Alphabet Keys
        'Q' => VC_Q_SHIFT,
        'q' => VC_Q,
        'W' => VC_W_SHIFT,
        'w' => VC_W,
        'E' => VC_E_SHIFT,
        'e' => VC_E,
        'R' => VC_R_SHIFT,
        'r' => VC_R,
        'T' => VC_T_SHIFT,
        't' => VC_T,
        'Y' => VC_Y_SHIFT,
        'y' => VC_Y,
        'U' => VC_U_SHIFT,
        'u' => VC_U,
        'I' => VC_I_SHIFT,
        'i' => VC_I,
        'O' => VC_O_SHIFT,
        'o' => VC_O,
        'P' => VC_P_SHIFT,
        'p' => VC_P,
        'A' => VC_A_SHIFT,
        'a' => VC_A,
        'S' => VC_S_SHIFT,
        's' => VC_S,
        'D' => VC_D_SHIFT,
        'd' => VC_D,
        'F' => VC_F_SHIFT,
        'f' => VC_F,
        'G' => VC_G_SHIFT,
        'g' => VC_G,
        'H' => VC_H_SHIFT,
        'h' => VC_H,
        'J' => VC_J_SHIFT,
        'j' => VC_J,
        'K' => VC_K_SHIFT,
        'k' => VC_K,
        'L' => VC_L_SHIFT,
        'l' => VC_L,
        'Z' => VC_Z_SHIFT,
        'z' => VC_Z,
        'X' => VC_X_SHIFT,
        'x' => VC_X,
        'C' => VC_C_SHIFT,
        'c' => VC_C,
        'V' => VC_V_SHIFT,
        'v' => VC_V,
        'B' => VC_B_SHIFT,
        'b' => VC_B,
        'N' => VC_N_SHIFT,
        'n' => VC_N,
        'M' => VC_M_SHIFT,
        'm' => VC_M,

        '-' => VC_MINUS,
        '_' => VC_UNDERSCORE,
        '=' => VC_EQUALS,
        '+' => VC_PLUS,

        '[' => VC_BRACKET_LEFT,
        ']' => VC_BRACKET_RIGHT,
        '{' => VC_BRACE_LEFT,
        '}' => VC_BRACE_RIGHT,
        '\\' => VC_BACK_SLASH,
        '|' => VC_BAR,

        ';' => VC_SEMICOLON,
        ':' => VC_COLON,
        '\'' => VC_APOSTROPHE,
        '\"' => VC_QUOTE,

        ',' => VC_COMMA,
        '<' => VC_LESS,
        '.' => VC_PERIOD,
        '>' => VC_GREATER,
        '/' => VC_SLASH,
        '?' => VC_QUESTION,

        // Keypad keys
        '0' => VC_KP_0,
        '1' => VC_KP_1,
        '2' => VC_KP_2,
        '3' => VC_KP_3,
        '4' => VC_KP_4,
        '5' => VC_KP_5,
        '6' => VC_KP_6,
        '7' => VC_KP_7,
        '8' => VC_KP_8,
        '9' => VC_KP_9,

        '/' => VC_KP_DIVIDE,
        '*' => VC_KP_MULTIPLY,
        '-' => VC_KP_SUBTRACT,
        '+' => VC_KP_ADD,
        '.' => VC_KP_DECIMAL,

        _ => panic!("Got unknown character!"),
    }
}
